### ISSUE TITLE
TODO LIST 

### ISSUE THREAD

**Issue by pevargasg** [pevargasg/TAMO#1]
**WEBSITE HAS BE LAUNCH ON JUNE 25TH!**

- [ ] BUY  DOMAIN (ASAP) 

- [ ] 3D logo of  TAMO (Matt)

- [ ] finish project pages (Pato)

- [ ] send computer graphics code to pato (Matt)

- [ ] finish all the websites from projects (Pato)

- [ ] upload project that are locally to cloud9 for online preview (Pato)

- [ ] BUSINESS CARDS FOR TAMO

- [ ] TALK TO YOUR CLASSMATE ABOUT THEIR WEBSITE ON MONDAY (Matt)

@mtcliatt
